---
name: Pod-FromActionscript
version: 0.51
author:
  - 'Clotho Advanced Media Inc., I<cpan@clotho.com>'
abstract: Convert Actionscript documentation to POD
license: perl
build_requires:
  Test::More: 0
provides:
  Pod::FromActionscript:
    file: lib/Pod/FromActionscript.pm
    version: 0.51
generated_by: Module::Build version 0.2611
